### ISSUE TITLE
NRE on Windows UWP

### ISSUE THREAD

**Issue by ozzy1873** [inthehand/InTheHand.Forms#8]
I'm seeing an occasional NRE. It's intermittent and I have not found a way to repro. Any ideas?

Fatal 04/06/2017 08:19:06 App_UnhandledException System.NullReferenceException: Arg_NullReferenceException
   at InTheHand.Forms.Platform.WinRT.MediaElementRenderer.Control_SeekCompleted(Object sender, UI.Xaml.RoutedEventArgs e)
   at Windows.UI.Xaml.Media.Imaging.DownloadProgressEventHandler.Invoke(Object sender, UI.Xaml.Media.Imaging.DownloadProgressEventArgs e)

**Comment by peterfoot** [comment]
I could see this happening if the renderer is detatched from the element and a seek operation is already in progress. This would mean the Element property would be null when the SeekCompleted handler is called. I will add some extra protection around this.

**Comment by peterfoot** [comment]
Closing as this should be addressed in 804 release
